const CONFIG = {
    titleWeb: "cho anh một lần sửa sai nha",
    introTitle: 'Ngân',
    introDesc: `anh biết mọi thứ là do anh gây ra, 
    bây giờ thật sự trong anh rất hối hận, 
    mong em có thể suy nghĩ lại và cho anh thêm một cơ hội để sửa lại lỗi lầm đó,
    thật sự bài học này quá đắt với a`,
    btnIntro: '^^HiHi^^',
    title: 'có gì thì anh và em cùng vượt qua có được không 🥰',
    desc: ':) ',
    btnYes: 'đồng ý <33',
    btnNo: 'Không nha',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại đồng ý yêu mình <3',
    btnReply: 'Gửi cho <3',
    reply: '                                                           ',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'cảm ơn em.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/messages/t/100038416873681' //link mess của các bạn. VD: https://m.me/nam.nodemy
}
